### ISSUE TITLE
FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable

### ISSUE THREAD

**Issue by szydell** [Delwing/arkadia-cfg-editor#1]
Hej,

na Fedorze mam problem z odpaleniem edytora. Przestał działać po upgrade albo kernela do 5.15.16, albo Fedory do 35.

```
"[23181:0124/134305.949602:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.\n"
```
# uname -a
Linux laPtak 5.15.16-200.fc35.x86_64 #1 SMP Thu Jan 20 15:38:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

nvidia-driver
Version      : 495.46

**Comment by Delwing** [comment]
Aplikacja przepisana, podbite wersje bibliotek mam nadzieję, że przy okazji rozwiążę i ten problem. Jak nie, to reopen ;]
